// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCommand(arg1) {
  return window['go']['main']['App']['DeleteCommand'](arg1);
}

export function DeleteHookBinding(arg1) {
  return window['go']['main']['App']['DeleteHookBinding'](arg1);
}

export function DeleteRedeem(arg1) {
  return window['go']['main']['App']['DeleteRedeem'](arg1);
}

export function GetRecentActivity() {
  return window['go']['main']['App']['GetRecentActivity']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function GetTwitchStatus() {
  return window['go']['main']['App']['GetTwitchStatus']();
}

export function ListActions() {
  return window['go']['main']['App']['ListActions']();
}

export function ListCommands() {
  return window['go']['main']['App']['ListCommands']();
}

export function ListHookBindings() {
  return window['go']['main']['App']['ListHookBindings']();
}

export function ListHooks() {
  return window['go']['main']['App']['ListHooks']();
}

export function ListRedeems() {
  return window['go']['main']['App']['ListRedeems']();
}

export function ListTwitchRewards() {
  return window['go']['main']['App']['ListTwitchRewards']();
}

export function LoginWithTwitch() {
  return window['go']['main']['App']['LoginWithTwitch']();
}

export function LogoutFromTwitch() {
  return window['go']['main']['App']['LogoutFromTwitch']();
}

export function SaveCommand(arg1) {
  return window['go']['main']['App']['SaveCommand'](arg1);
}

export function SaveHookBinding(arg1) {
  return window['go']['main']['App']['SaveHookBinding'](arg1);
}

export function SaveRedeem(arg1) {
  return window['go']['main']['App']['SaveRedeem'](arg1);
}

export function SetPort(arg1) {
  return window['go']['main']['App']['SetPort'](arg1);
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function UnwatchHook(arg1) {
  return window['go']['main']['App']['UnwatchHook'](arg1);
}

export function WatchHook(arg1) {
  return window['go']['main']['App']['WatchHook'](arg1);
}
