// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {sail} from '../models';
import {config} from '../models';
import {twitchapi} from '../models';

export function DeleteCommand(arg1:string):Promise<void>;

export function DeleteHookBinding(arg1:string):Promise<void>;

export function DeleteRedeem(arg1:string):Promise<void>;

export function GetRecentActivity():Promise<Array<main.ActivityEvent>>;

export function GetServerStatus():Promise<main.ServerStatus>;

export function GetTwitchStatus():Promise<main.TwitchStatus>;

export function ListActions():Promise<Array<sail.ActionInfo>>;

export function ListCommands():Promise<Array<config.Command>>;

export function ListHookBindings():Promise<Array<config.HookBinding>>;

export function ListHooks():Promise<Array<sail.HookInfo>>;

export function ListRedeems():Promise<Array<config.Redeem>>;

export function ListTwitchRewards():Promise<Array<twitchapi.CustomReward>>;

export function LoginWithTwitch():Promise<void>;

export function LogoutFromTwitch():Promise<void>;

export function SaveCommand(arg1:config.Command):Promise<void>;

export function SaveHookBinding(arg1:config.HookBinding):Promise<void>;

export function SaveRedeem(arg1:config.Redeem):Promise<void>;

export function SetPort(arg1:number):Promise<void>;

export function StartServer():Promise<void>;

export function StopServer():Promise<void>;

export function UnwatchHook(arg1:string):Promise<void>;

export function WatchHook(arg1:string):Promise<void>;
