name: compile
on:
  push:
  pull_request:
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: denoland/setup-deno@v1
      with:
        deno-version: vx.x.x
    - uses: actions/checkout@v3
    - name: Compile
      run: |
        deno compile --target aarch64-apple-darwin --allow-net --allow-read -o build/twitch-json-sail-mac-aarch64 examples/twitch_json_sail.ts
        deno compile --target x86_64-apple-darwin --allow-net --allow-read -o build/twitch-json-sail-mac-x86_64 examples/twitch_json_sail.ts
        deno compile --target x86_64-pc-windows-msvc --allow-net --allow-read -o build/twitch-json-sail-windows-x86_64.exe examples/twitch_json_sail.ts
        deno compile --target x86_64-unknown-linux-gnu --allow-net --allow-read -o build/twitch-json-sail-linux-x86_64 examples/twitch_json_sail.ts
        deno compile --target x86_64-pc-windows-msvc --allow-net --allow-read -o build/sammi-sail-windows-x86_64.exe examples/sammi_sail.ts
    - name: Upload twitch-json-sail macOS aarch64
      uses: actions/upload-artifact@v3
      with:
        name: twitch-json-sail-mac-aarch64
        path: build/twitch-json-sail-mac-aarch64
    - name: Upload twitch-json-sail macOS x86_64
      uses: actions/upload-artifact@v3
      with:
        name: twitch-json-sail-mac-x86_64
        path: build/twitch-json-sail-mac-x86_64
    - name: Upload twitch-json-sail Windows x86_64
      uses: actions/upload-artifact@v3
      with:
        name: twitch-json-sail-windows-x86_64.exe
        path: build/twitch-json-sail-windows-x86_64.exe
    - name: Upload sammi-sail Windows x86_64
      uses: actions/upload-artifact@v3
      with:
        name: sammi-sail-windows-x86_64.exe
        path: build/sammi-sail-windows-x86_64.exe
    - name: Upload twitch-json-sail Linux x86_64
      uses: actions/upload-artifact@v3
      with:
        name: twitch-json-sail-linux-x86_64
        path: build/twitch-json-sail-linux-x86_64
 
